[project]
name = "workshop-pdf-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cohere>=5.16.1",
    "numpy>=2.2.6",
    "pdf2image>=1.17.0",
    "weaviate-client>=4.16.0",
]
